function kDS = my_knownDataSets()
%MY_KNOWNDATASETS returns known definitions of data sets as a struct.
%    Add your data set definitions

%   TU Berlin --- Fachgebiet Regelungssystem
%   Author: Markus Valtin
%   Copyright © 2017 Markus Valtin. All rights reserved.
%
%   This program is free software: you can redistribute it and/or modify it under the terms of the 
%   GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
%
%   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

kDS = struct();

kDS.definition_XXX = struct( ...
    'setup', struct(    'type', 'rawIMU_Config', ...
                        'name', 'test_Config', ...
                        'version', [1], ...
                        'description', 'Just a test Config to check all the options. -> tmt_getDataFromFile will ignore field names setup !'), ...
    'nestedStruct', struct( ...
        'time', [1], ...
        'IMU_1', struct( 'ACC', [2  3  4] )  ...
    ),  ...
    'valid', [5], ...
    'rest_data', [6:10] ...
);

kDS.definition_XYZ = struct( ...
    'setup', 'Just another configuration to demonstrate the principle. Add as many as you like...', ...
    'time', [1], ...
    'IMU_1', struct( 'ACC', [2  3  4], 'GYR', [5,6,7], 'MAG', [8,9,10] ),  ...
    'valid', [11] ...
);

% add your definitions here

end
